spark.hadoop.fs.azure.account.auth.type.nhom5storage.dfs.core.windows.net SharedKey
spark.hadoop.fs.azure.account.key.nhom5storage.dfs.core.windows.net ${env.AZURE_STORAGE_ACCESS_KEY}
spark.master yarn
spark.submit.deployMode client
spark.jars.packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0